config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users

  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"
  get "search" => "searches#search"

  resources :books, only: [:index, :new, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
 
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!



  def search
    @range = params[:range]
    @word = params[:word]

    if @range == "user"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search.html.erb
<% if @range == "user" %>

  <h2>Users serch for "<%= @word %>"</h2>
<% else %>
  <h2>Books serch for "<%= @word %>"</h2>
<% end %>






<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "user" %>
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><td><%= image_tag user.get_profile_image %></td></td>
        <td><%= link_to user_path(user.id) do %>
            <%= user.name %>
            <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  <% else %>
  <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= image_tag book.user.get_profile_image %></td>
        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
      </tr>
      <% end %>
  </tbody>
  <% end %>
</table>